language: python
python: 
  - "3.9"

branches:
  only:
  - main

# env:
#   - GITHUB_TOKEN: $secrets.GITHUB_TOKEN

jobs:
  include:
    - stage: build and deploy pages
      before_install:
        - rm ~/.netrc
      install:
        - pip install quarto-cli
      script:
        - quarto render --output-dir build
#      script: 
#        - quarto publish gh-pages --no-prompt --no-browser --token $GITHUB_TOKEN

      before_deploy: 
      - rvm --default use 2.7.6
      deploy:
      - provider: pages
        edge:
          branch: v1.10.16
        github_url: github.ibm.com
        github_token: $GITHUB_TOKEN
        target_branch: gh-pages
        skip_cleanup: true
        local_dir: build
        on:
          branch: main
    - stage: sync to public
      if: type != pull_request
      before_install:
        - export GITHUB_PUB_URI=$(echo $GITHUB_PUBLIC | sed "s/\/github.com\//\/$PUBLIC_TOKEN\@github.com\//")
        - export GITHUB_ENTERPRISE=$(echo $GITHUB_PUBLIC | sed "s/\/github.com\//\/$GITHUB_TOKEN\@github.ibm.com\//")
        - git clone $GITHUB_ENTERPRISE /tmp/repo
        - cd /tmp/repo
      script:
        - git remote set-url origin $GITHUB_PUB_URI
        - git push origin main --force


stages:
  - build and deploy pages
  - sync to public
